### ISSUE TITLE
Html dist package ?

### ISSUE THREAD

**Issue by xlievo** [azouaoui-med/angular-pro-sidebar#7]
This is the best sidebar I've found. Do you have an HTML version? Can you provide a package like dist? Thank you for your efforts!

**Comment by ALEXOTANO** [comment]
It is the best! If you are familiar with angular, you may want to try Angular elements (Reusable HTML/JS elements), haven't do it but I know it can be done.

**Comment by xlievo** [comment]
I have done it. Thanks again!
This is the best sidebar!
